# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy Angular and Docker

on:
  push:
    branches: [ master ]

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.date }}
    steps:
      - id: step1
        run: echo "::set-output name=date::lordgasmic/webapp"

  build:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build with Docker
        run: docker build . --file Dockerfile --tag ${{ needs.vars.outputs.output1 }}
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Push
        run: docker push ${{ needs.vars.outputs.output1 }}
